# Generated by Django 4.2.11 on 2024-04-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_active_book_auther_book_category_book_pages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='photo_auther',
            new_name='photo_author',
        ),
    ]
