# Generated by Django 4.2.11 on 2024-07-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_auther_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='retal_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
