# Generated by Django 4.2.11 on 2024-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_retal_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='profit_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='profits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
